import http from 'http';
import https from 'https';

const PORT = 49152; // Registered port range, unlikely to conflict

export const progressCache = {};

export function updateProgress(id, data) {
  if (data === null) {
    delete progressCache[id];
  } else {
    progressCache[id] = { ...progressCache[id], ...data };
  }
}

global.proxyHeadersCache = new Map();

export function startLocalServer({ onUrlReceived, onFetchInfo, onOpenFolder, onCancelDownload }) {
  const server = http.createServer(async (req, res) => {
    // Enable CORS for the Chrome Extension
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Range');
    res.setHeader('Access-Control-Expose-Headers', 'Content-Length, Content-Range, Accept-Ranges');

    // Handle preflight requests
    if (req.method === 'OPTIONS') {
      res.writeHead(204);
      res.end();
      return;
    }

    if (req.method === 'POST') {
      let body = '';
      req.on('data', chunk => body += chunk.toString());
      
      req.on('end', async () => {
        try {
          const data = JSON.parse(body);
          
          if (req.url === '/download') {
            if (data && data.url && data.url.startsWith('http')) {
              onUrlReceived(data.url, data.autoDownload || false, data.quality || 'best');
              res.writeHead(200, { 'Content-Type': 'application/json' });
              res.end(JSON.stringify({ success: true }));
            } else {
              res.writeHead(400, { 'Content-Type': 'application/json' });
              res.end(JSON.stringify({ error: 'Invalid URL' }));
            }
          } 
          else if (req.url === '/fetch-info' && onFetchInfo) {
            if (data && data.url && data.url.startsWith('http')) {
              const info = await onFetchInfo(data.url);
              res.writeHead(200, { 'Content-Type': 'application/json' });
              res.end(JSON.stringify(info));
            } else {
              res.writeHead(400, { 'Content-Type': 'application/json' });
              res.end(JSON.stringify({ error: 'Invalid URL' }));
            }
          }
          else if (req.url === '/open-folder' && onOpenFolder) {
            if (data && data.id) {
              onOpenFolder(data.id);
              res.writeHead(200, { 'Content-Type': 'application/json' });
              res.end(JSON.stringify({ success: true }));
            } else {
              res.writeHead(400, { 'Content-Type': 'application/json' });
              res.end(JSON.stringify({ error: 'Invalid ID' }));
            }
          }
          else if (req.url === '/cancel' && onCancelDownload) {
            if (data && data.id) {
              onCancelDownload(data.id);
              res.writeHead(200, { 'Content-Type': 'application/json' });
              res.end(JSON.stringify({ success: true }));
            } else {
              res.writeHead(400, { 'Content-Type': 'application/json' });
              res.end(JSON.stringify({ error: 'Invalid ID' }));
            }
          }
          else {
            res.writeHead(404);
            res.end();
          }
        } catch (e) {
          console.error(e);
          res.writeHead(400, { 'Content-Type': 'application/json' });
          res.end(JSON.stringify({ error: 'Invalid request or fetching failed' }));
        }
      });
    } else if (req.method === 'GET' && req.url === '/progress') {
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ downloads: Object.values(progressCache) }));
    } else if (req.method === 'GET' && req.url.startsWith('/preview?')) {
      // Proxy endpoint: streams a remote video URL through localhost to bypass CORS.
      try {
        const params = new URL(req.url, 'http://localhost');
        const targetUrl = params.searchParams.get('url');
        if (!targetUrl) {
          res.writeHead(400);
          res.end('Missing url parameter');
          return;
        }

        const browserSentRange = !!req.headers.range;
        const proxyHeaders = {};
        
        // Retrieve headers generated by yt-dlp to satisfy YouTube WAF
        const cachedHeaders = global.proxyHeadersCache ? global.proxyHeadersCache.get(targetUrl) : null;
        if (cachedHeaders) {
          console.log(`[Proxy] HIT cache for ${targetUrl.substring(0, 30)}...`);
          for (const [k, v] of Object.entries(cachedHeaders)) {
            proxyHeaders[k] = v;
          }
        } else {
          console.log(`[Proxy] MISS cache for ${targetUrl.substring(0, 30)}...`);
        }

        // Forward safe headers from the browser if they aren't already set by yt-dlp
        const safeHeaders = ['user-agent', 'accept', 'accept-language'];
        for (const h of safeHeaders) {
          if (req.headers[h] && !proxyHeaders[h] && !proxyHeaders[h.toLowerCase()] && !proxyHeaders[h.replace(/(^\w|-\w)/g, c => c.toUpperCase())]) {
            proxyHeaders[h] = req.headers[h];
          }
        }

        // Forward Range header for seeking support.
        // CRITICAL: YouTube returns 403 for non-Range requests!
        // Chromium's <video> sends an initial probe without Range, so we must inject one.
        // Handle Range header - YouTube CDN rejects open-ended ranges (bytes=X-) with 403!
        // We MUST chunk them into bounded requests (e.g., 10MB chunks)
        const CHUNK_SIZE = 10 * 1024 * 1024; // 10MB
        if (req.headers.range) {
          const match = req.headers.range.match(/bytes=(\d+)-(\d*)/);
          if (match) {
            const start = parseInt(match[1], 10);
            const end = match[2] ? parseInt(match[2], 10) : start + CHUNK_SIZE;
            proxyHeaders['Range'] = `bytes=${start}-${end}`;
          } else {
            proxyHeaders['Range'] = req.headers.range;
          }
        } else {
          proxyHeaders['Range'] = `bytes=0-${CHUNK_SIZE}`;
        }

        https.get(targetUrl, { headers: proxyHeaders }, (upstream) => {
          // Forward status code and relevant headers
          const responseHeaders = {
            'Content-Type': upstream.headers['content-type'] || 'video/mp4',
            'Accept-Ranges': 'bytes',
            'Access-Control-Allow-Origin': '*',
            'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
            'Access-Control-Allow-Headers': 'Content-Type, Range',
            'Access-Control-Expose-Headers': 'Content-Length, Content-Range, Accept-Ranges'
          };
          let statusCode = upstream.statusCode;
          console.log(`[Proxy] Upstream returned ${statusCode} for range ${proxyHeaders['Range']}`);

          if (browserSentRange) {
            if (upstream.headers['content-length']) responseHeaders['Content-Length'] = upstream.headers['content-length'];
            if (upstream.headers['content-range']) responseHeaders['Content-Range'] = upstream.headers['content-range'];
          } else {
            // Chromium probe without Range -> we injected bytes=0-1024 -> YouTube returned 206.
            // Chromium rejects 206 if it didn't ask for it (Error 4). Convert to 200 OK.
            if (statusCode === 206) {
              statusCode = 200;
              if (upstream.headers['content-range']) {
                const match = upstream.headers['content-range'].match(/\/(\d+)/);
                if (match) responseHeaders['Content-Length'] = match[1];
              }
            } else if (upstream.headers['content-length']) {
              responseHeaders['Content-Length'] = upstream.headers['content-length'];
            }
          }

          res.writeHead(statusCode, responseHeaders);
          
          if (browserSentRange) {
            upstream.pipe(res);
          } else {
            // CRITICAL: Keep the connection open for the initial probe!
            // If we close it after 1024 bytes, Chromium treats it as a network error (Error 4).
            // By keeping it open, Chromium reads the MP4 headers and cleanly aborts the request itself.
            upstream.pipe(res, { end: false });
          }
        }).on('error', (err) => {
          console.error('Preview proxy error:', err.message);
          res.writeHead(502);
          res.end('Proxy error');
        });
      } catch (e) {
        res.writeHead(500);
        res.end('Server error');
      }
    } else {
      res.writeHead(404);
      res.end();
    }
  });

  server.on('error', (err) => {
    console.error('Local Extension Server Error:', err);
    // Ignore EADDRINUSE silently, just means the server is already running (e.g., dev hot reload)
  });

  server.listen(PORT, '127.0.0.1', () => {
    console.log(`Local Extension Server listening on http://127.0.0.1:${PORT}`);
  });

  return server;
}
